# Generated by Django 5.2.7 on 2025-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('case_background', 'Case Background'), ('architecture', 'Architecture'), ('how_cloudflare_help', 'How Cloudflare Helps'), ('business_value', 'Business Value')], help_text='Type of presentation section', max_length=50, unique=True)),
                ('content_json', models.JSONField(default=dict, help_text='JSON content structure for the section')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Presentation Section',
                'verbose_name_plural': 'Presentation Sections',
                'ordering': ['section_type'],
            },
        ),
    ]
